// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekrtrvjmonzekgwtavoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcnRydmptb256ZWtnd3Rhdm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTU1MzYsImV4cCI6MjA1NTE5MTUzNn0.t0qv8f4Ep6esCQsSzCV_xyBtJDBL29IpuG4ieJ_Va3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);